//
// Created by zzqni on 2024/4/18.
//

#ifndef ANDROIDFRAMEWORKTEST_COMMONSTRING_H
#define ANDROIDFRAMEWORKTEST_COMMONSTRING_H

#define MAXLENGTH 181920

void printArray(int array[], int count);

#endif //ANDROIDFRAMEWORKTEST_COMMONSTRING_H
